### PR TITLE
adding listen instructions for tutorial

### PR DESCRIPTION
**Pull request by joshTlil**
Adding the tutorial instructions for the user

### CODE REVIEW

**Review by brouiller — APPROVED** [review]
looks good

**Review by Leci1259 — APPROVED** [review]
Looks good. Just need to fix line 69 from API Demo to API Tutorial

**Review by DeeScrump — APPROVED** [review]
Line 69 updated to API Tutorial, so good to go!

**Review by Leci1259 — APPROVED** [review]
Looks good. Line 69 fixed

**Pull request merged**
