### PR TITLE
Feature/tutorial

### PR DESCRIPTION
**Pull request by DeeScrump**
Made updates to the demo.html

### CODE REVIEW

**Review by joshTlil — APPROVED** [review]
Everything looks good just need to align them

**Review by Leci1259 — CHANGES_REQUESTED** [review]
looks good. Just fix formatting and repush

**Comment by DeeScrump** [comment]
Updated formatting

**Comment by DeeScrump** [comment]
removed css styling changes

**Review by joshTlil — APPROVED** [review]
Everything looks well organized and neat

**Review by Leci1259 — APPROVED** [review]
Looks good

**Review by brouiller — APPROVED** [review]
looks good

**Pull request merged**
